---

- name: ipsec | install
  apt:
    pkg: "{{ item  }}"
    state: present
    update_cache: yes
    cache_valid_time: 3600
  with_items:
    - ipsec-tools
    - racoon
  become: yes
  become_method: sudo
